# Generated by Django 4.0.5 on 2022-07-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.ManyToManyField(to='main_app.hobbies'),
        ),
    ]
