# Generated by Django 4.0.5 on 2022-07-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_person_bio_alter_person_discord_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profpic',
            new_name='Photo',
        ),
    ]
